title:        API Integration
description:  A sample API integration page showing other integrations available with an API.
url:          http://api.integration.tool.apievangelist.com/
raw_url:      https://raw.githubusercontent.com/api-evangelist-tools/api-integration/master/_data/
version:      1.1.1

author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".DS_Store"]

github_user: api-evangelist-tools
github_repo: api-integration

production_url : http://api.integration.tool.apievangelist.com

image : http://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png
imagesecure : https://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

integration_spreadsheet_key: 1TsoBeTAgwdE0FcSlrB8riu7aTTlsF48WSNsI3RmmlRc
