Swagger: "2.0"
info:
  title: OpenAPI Toolbox API
  description: Machine readable access to the code and definitions in the OpenAPI Toolbox.
  version: 1.0.0
host: openapi.toolbox.apievangelist.com
basePath: /apis
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /tools:
    get:
      summary: Get Tools
      description: Returns all the tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
  /tools/clients:
    get:
      summary: Get All Client Tools
      description: Returns all the client tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Clients
  /tools/documentation:
    get:
      summary: Get Documentation Tools
      description: Returns all the documentation tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Documentation
  /tools/editors/:
    get:
      summary: Get Editor Tools
      description: Returns all the editor tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Editors
  /tools/generators/:
    get:
      summary: Get Generator Tools
      description: Returns all the generator tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Generators
  /tools/java:
    get:
      summary: Get Java Tools
      description: Returns all the Java tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Java
  /tools/javascript/:
    get:
      summary: Get JavaScript Tools
      description: Returns all the JavaScript tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - JavaScript
  /tools/nodejs/:
    get:
      summary: Get Node.js Tools
      description: Returns all the Node.js tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Node.js
  /tools/php/:
    get:
      summary: Get PHP Tools
      description: Returns all the PHP tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - PHP
  /tools/python/:
    get:
      summary: Get Python Tools
      description: Returns all the Python tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Python
  /tools/ruby/:
    get:
      summary: Get Ruby Tools
      description: Returns all the ruby tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Ruby
  /tools/servers/:
    get:
      summary: Get Server Tools
      description: Returns all the server tools in the toolbox.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/tool'
      tags:
        - Tools
        - OpenAPI
        - Servers
definitions:
  tool:
    properties:
      title:
        description: The title of the tool.
        type: string
      details:
        description: The details for the tool.
        type: string
      url:
        description: A URL to find more information on tool.
        type: string
      image:
        description: An image to represent the tool.
        type: string
      orgs:
        description: The organization or entity behind the tool.
        type: string
      type:
        description: The type of tool.
        type: string
      tags:
        description: Comma separated list of tags applying to tool.
        type: string
      license:
        description: The license name for the tool.
        type: string
      license_url:
        description: The url for the tool license.
        type: string
