Swagger: "2.0"
info:
  title: API Integrations
  description: Machine readable access to the API integrations available.
  version: 1.0.0
host: api.integration.tool.apievangelist.com
basePath: /apis
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /integrations/:
    get:
      summary: Get Integrations
      description: Returns all the integrations on this platform..
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/integration'
      tags:
        - Integrations
        - API
  /integrations/social/:
    get:
      summary: Get All Social Integrations
      description: Returns all the social integrations on this platform..
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/integration'
      tags:
        - Integrations
        - API
        - Social
  /integrations/storage/:
    get:
      summary: Get Storage Integrations
      description: Returns all the storage integrations on this platform..
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/integration'
      tags:
        - Integrations
        - API
        - Storage
  /integrations/payments/:
    get:
      summary: Get Payment Integrations
      description: Returns all the payment integrations on this platform..
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/integration'
      tags:
        - Integrations
        - API
        - Payments
  /integrations/spreadsheets/:
    get:
      summary: Get Spreadsheet Integrations
      description: Returns all the spreadsheet integrations on this platform..
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/integration'
      tags:
        - Integrations
        - API
        - Spreadsheets
definitions:
  integration:
    properties:
      name:
        description: The name of the API integration.
        type: string
      identifier:
        description: A unique identiefer for the API integration.
        type: string
      url:
        description: A URL to find more information about integration.
        type: string
      description:
        description: A descripton of the integration.
        type: string
      image:
        description: An image representation for an integration.
        type: string
      imagewidth:
        description: An image width for the integration.
        type: integer
      category:
        description: A category for the integration.
        type: string
      brand:
        description: A brand associated with the integration.
        type: string
