---
layout: none
---
{% assign categorylist = '' %}
{% for integration in site.data.integrations %}
  {% assign category = integration.category | downcase %}
  {% if categorylist contains category %}
  {% else %}
    {% assign categorylist = categorylist | append:',' | append: category %}
  {% endif %}
{% endfor %}
--{{ categorylist }}--
{% assign categoryArray = categorylist | split: "," %}
swagger: 2.0
info:
  title: {{ site.title }}
  description: {{ site.description }}
  termsOfService: {{ site.url }}/terms-of-service/
  contact:
    name: {{ site.author.name }}
    url: {{ site.author.url }}
    email: {{ site.author.email }}
  version: {{ site.version }}
host: {{ site.url }}
basePath: /apis/{{ site.api_resource }}
schemes:
 - http
produces:
 - application/json
paths:{% for path in categoryArray %}{% if path != '' %}
  /{{ path }}/:
    get:
      summary: {{ path | capitalize }}
      description: This is a list of {{ path }} data.
      operationId: get{{ path | capitalize }}
      responses:
        '200':
          description: A succesful {{ path }} response.
          schema:
            type: array
            items:
              $ref: "#/definitions/{{ site.api_resource }}"
      tags:
        - {{ path | capitalize }}{% endif %}{% endfor %}
definitions:
  {{ site.api_resource }}:
    properties:{% for i in site.data.integrations[1] %}
      {% if i[0] contains 1 or i[0] contains 2 or i[0] contains 3 or i[0] contains 4 or i[0] contains 5 or i[0] contains 6 or i[0] contains 7 or i[0] contains 8 or i[0] contains 9 %}
        NUMBER!
      {% endif %}
      {{ i[0] }}:
        test1: {{ i[1] }}
        description: 'The {{ i[0] }} for {{ site.api_resource }}'
        type: {% if test_type contains '"' %}string{% else %}number{% endif %}{% endfor %}
